"""Pure, bounded, runtime-neutral Strategy Core V3 semantics."""

from .canonical import CanonicalValue, canonical_bytes, canonical_sha256
from .context import (
    BoundedContextPayload,
    DecisionContextV3,
    DecisionTrigger,
    SourceEvidence,
    TriggerKind,
)
from .profile import (
    CANONICAL_PROFILE,
    CANONICAL_PROFILE_VERSION,
    MAX_CANONICAL_BYTES,
    MAX_CANONICAL_NESTING,
    MAX_DIAGNOSTIC_MESSAGE_BYTES,
    MAX_DIAGNOSTICS,
    MAX_EVIDENCE,
    MAX_IDENTIFIER_BYTES,
    MAX_INTENTS,
    MAX_REASON_CODE_BYTES,
    MAX_TIMER_REQUESTS,
    MAX_TIMER_SEMANTICS_BYTES,
    CanonicalError,
    EpochNanoseconds,
    FixedDecimal,
    ReasonCode,
    TimerKey,
)
from .result import (
    CancelTimerRequest,
    ContractSide,
    DecisionOutcome,
    DecisionResultProfile,
    DecisionResultV3,
    Diagnostic,
    DiagnosticSeverity,
    OrderAction,
    ScheduleTimerRequest,
    StrategyEvidence,
    StrategyOrderIntent,
    TimerRequest,
    calculate_result_profile,
)

__all__ = [
    "CANONICAL_PROFILE",
    "CANONICAL_PROFILE_VERSION",
    "MAX_CANONICAL_BYTES",
    "MAX_CANONICAL_NESTING",
    "MAX_DIAGNOSTIC_MESSAGE_BYTES",
    "MAX_DIAGNOSTICS",
    "MAX_EVIDENCE",
    "MAX_IDENTIFIER_BYTES",
    "MAX_INTENTS",
    "MAX_REASON_CODE_BYTES",
    "MAX_TIMER_REQUESTS",
    "MAX_TIMER_SEMANTICS_BYTES",
    "BoundedContextPayload",
    "CancelTimerRequest",
    "CanonicalError",
    "CanonicalValue",
    "ContractSide",
    "DecisionContextV3",
    "DecisionOutcome",
    "DecisionResultProfile",
    "DecisionResultV3",
    "DecisionTrigger",
    "Diagnostic",
    "DiagnosticSeverity",
    "EpochNanoseconds",
    "FixedDecimal",
    "OrderAction",
    "ReasonCode",
    "ScheduleTimerRequest",
    "SourceEvidence",
    "StrategyEvidence",
    "StrategyOrderIntent",
    "TimerKey",
    "TimerRequest",
    "TriggerKind",
    "calculate_result_profile",
    "canonical_bytes",
    "canonical_sha256",
]
